---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggpubr)
```


```{r}
df <- readRDS("/scripts/11b_RunClusteringRes0.4/out_obj/allintegratedClustered_Seurat2.RDS")

outdir <- "/scripts/0_Figures/Fig1_proportions/Panels/Fig1C_Proportions/outdir/"
```

```{r}
palette_sample = c(`blood_SCI_veh` = "#3C0D03",
                   `blood_SCI_ivig` = "#99280A",
                    `blood_sham_veh` = "#EC9543",
                   `blood_naive_veh` = "#F3C34D",
                   `cord_SCI_veh` = "#0A3351",
                   `cord_SCI_ivig` = "#3274A3")

palette_clust = c(
            # T cells
            `0` = "gold", #CD4
            `1` = "orangered", #Treg
            `3` = "deeppink2", #naive_CD8
            `4` = "darkorchid4", #mem_CD8
            `5` = "chocolate1", #naive_CD4
            # B cells
            `2` = "peachpuff4", #naive_memB 1+2 (1)
            `8` = "peru", #naive_memB 1+2 (2)
            # NKT
            `6` = "limegreen", #NKT_DC
            `7` = "forestgreen", #NKT_B & NKT_DC
            # other
            `9` = "darkturquoise", #basophil
            `10` = "navyblue") #neutrophil
```

What is the makeup of each cluster?

```{r}
data <- as.data.frame(table(df[[c("integrated_snn_res.0.4", "sample")]]))
data <- reshape2::melt(data)
```

```{r}
data$sample <- factor(data$sample, levels = c("blood_SCI_veh", "blood_SCI_ivig", "blood_sham_veh", "blood_naive_veh", "cord_SCI_veh", "cord_SCI_ivig"))

write.table(data, file = paste0(outdir, "clusterwise_samplecounts.txt"), sep = "\t", quote = FALSE, col.names = NA)

ggplot(data, aes(fill = sample, y = value, x = integrated_snn_res.0.4)) +
  geom_bar(position = "stack", stat = "identity") +
   scale_fill_manual(values = palette_sample) +
  theme_bw()
ggsave(filename = paste0(outdir, "samplebar_all_number.pdf"), width = 6, height = 3)

ggplot(data, aes(fill = sample, y = value, x = integrated_snn_res.0.4)) +
  geom_bar(position = "fill", stat = "identity") +
   scale_fill_manual(values = palette_sample) +
  theme_bw()
ggsave(filename = paste0(outdir, "samplebar_all_percent.pdf"), width = 6, height = 3)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) +
  geom_bar(position = "stack", stat = "identity") +
   scale_fill_manual(values = palette_sample) +
  theme_bw()
ggsave(filename = paste0(outdir, "samplebar_blood_number.pdf"), width = 6, height = 3)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) +
  geom_bar(position = "fill", stat = "identity") +
   scale_fill_manual(values = palette_sample) +
  theme_bw()
ggsave(filename = paste0(outdir, "samplebar_blood_percent.pdf"), width = 6, height = 3)

data[grep("cord", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) +
  geom_bar(position = "stack", stat = "identity") +
   scale_fill_manual(values = palette_sample) +
  theme_bw()
ggsave(filename = paste0(outdir, "samplebar_cord_number.pdf"), width = 6, height = 3)

data[grep("cord", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) +
  geom_bar(position = "fill", stat = "identity") +
   scale_fill_manual(values = palette_sample) +
  theme_bw()
ggsave(filename = paste0(outdir, "samplebar_cord_percent.pdf"), width = 6, height = 3)
```



Flip the data the other way, plot each sample and break down by cluster

```{r}
ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw()
ggsave(filename = paste0(outdir, "legend.pdf"), width = 4, height = 4)

ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_all_number.pdf"), width = 4, height = 4)

ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_all_percent.pdf"), width = 4, height = 4)


data[grep("cord", data$sample),] %>% ggplot(aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_cord_number.pdf"), width = 4, height = 4)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_blood_number.pdf"), width = 4, height = 4)
```

# same thing but grouped by order of clusters (group biological functions)

```{r}
palette_clust = c(
            # T cells
            `0` = "gold", #CD4
            `1` = "orangered", #Treg
            `3` = "deeppink2", #naive_CD8
            `4` = "darkorchid4", #mem_CD8
            `5` = "chocolate1", #naive_CD4
            # B cells
            `2` = "peachpuff4", #naive_memB 1+2 (1)
            `8` = "peru", #naive_memB 1+2 (2)
            # NKT
            `6` = "limegreen", #NKT_DC
            `7` = "forestgreen", #NKT_B & NKT_DC
            # other
            `9` = "darkturquoise", #basophil
            `10` = "navyblue") #neutrophil


data$integrated_snn_res.0.4 <- factor(data$integrated_snn_res.0.4, levels = c(0, 1, 3, 4, 5, 2, 8, 6, 7, 9, 10)) #T cells (0, 1, 3, 4, 5), B cells (2, 8), NKT (6, 7), basophil (9), neutrophil (10)

ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw()
ggsave(filename = paste0(outdir, "legend_regroup.pdf"), width = 4, height = 4)

ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_all_number_regroup.pdf"), width = 4, height = 4)

ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_all_percent_regroup.pdf"), width = 4, height = 4)


data[grep("cord", data$sample),] %>% ggplot(aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_cord_number_regroup.pdf"), width = 4, height = 4)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette_clust) +
  theme_bw() + 
  NoLegend()
ggsave(filename = paste0(outdir, "clusterbar_blood_number_regroup.pdf"), width = 4, height = 4)
```

