---
title: "R Notebook"
output: html_notebook
---

# just edit for each file and run

```{r}
library(dplyr)
```

```{r}
outdir <- "/scripts/13b_ProcessForGO/Samplewise/4.1_splitIntoVennSegments/outdir/"

sampleID <- "4.1_SCIvsshamnaive_blood"

genelist <- read.delim("/scripts/13b_ProcessForGO/Samplewise/outdir/4.1_SCIvsshamnaive_blood_Markers_KeepSeparate_dropRbMt.txt")
```

# split into up and down

```{r}
# split into up and down
df_noRb_down <- genelist %>% filter(direction == "down")
df_noRb_up <- genelist %>% filter(direction == "up")
```


```{r}
##up_list <- split(df_noRb_up$gene, df_noRb_up$cluster)
# up_list <- split(df_noRb_up$analysisID, df_noRb_up$gene)
# up_table <- as.data.frame(sapply(up_list, function(x) paste(sort(x), collapse="_")))
# colnames(up_table) <- "groups"
# up_table$genes <- rownames(up_table)
# up_table2 <- split(up_table$genes, up_table$groups)
```

```{r}
GetVennSegments <- function(DEtable, fileID) {
  # list the analysis/analyses that each gene is found in
  GeneHitList <- split(DEtable$analysisID, DEtable$gene)
  # sort the analysis names alphabetically, concatenate and convert to table format
  GeneHitTable <- as.data.frame(sapply(GeneHitList, function(x) paste(sort(x), collapse="_")))
  # modify the table columns
  colnames(GeneHitTable) <- "groups"
  GeneHitTable$genes <- rownames(GeneHitTable)
  # save
  write.table(GeneHitTable, file = paste0(outdir, fileID, "_VennSegments.txt"), sep = "\t", quote = FALSE, col.names = NA)
  # convert table to a count of hits per segment
  counts <- as.data.frame(table(GeneHitTable$groups))
  colnames(counts) <- c("categories", "Freq")
  write.table(counts, file = paste0(outdir, fileID, "_VennSegmentCounts.txt"), sep = "\t", quote = FALSE, col.names = NA)
  # make a list of each possible Venn segment and the genes in it (absent segments will be missing)
  GeneHitList_new <- split(GeneHitTable$genes, GeneHitTable$groups)
  return(GeneHitList_new)
}
```

```{r}
down_segments <- GetVennSegments(df_noRb_down, "df_noRb_down")
up_segments <- GetVennSegments(df_noRb_up, "df_noRb_up")
```

