---
title: "Subset humanised mouse data"
output: html_notebook
---

```{r}
library(Seurat)
```

```{r}
outdir <- "/scripts/17_MetacellVehicleOnly/vehicle_subtypes/11.1_ExtractClusters/out/"
```

```{r}
fullseurat <- readRDS("/scripts/17_MetacellVehicleOnly/vehicle/11.1a_ReplotUMAP/out_obj/ReplotUMAP_Seurat.RDS")
# the correct clusters here are clusters_wholedataset ("integrated_snn_res.0.4" in the original dataset)
palette_clust = c(
            # T cells
            `0` = "gold", #CD4
            `1` = "orangered", #Treg
            `3` = "deeppink2", #naive_CD8
            `4` = "darkorchid4", #mem_CD8
            `5` = "chocolate1", #naive_CD4
            # B cells
            `2` = "peachpuff4", #naive_memB 1+2 (1)
            `8` = "peru", #naive_memB 1+2 (2)
            # NKT
            `6` = "limegreen", #NKT_DC
            `7` = "forestgreen", #NKT_B & NKT_DC
            # other
            `9` = "darkturquoise", #basophil
            `10` = "navyblue") #neutrophil
sampleID <- "Tcells"
```

# Plot the UMAP

```{r}
DimPlot(fullseurat, cols = palette_clust, group.by = "clusters_wholedataset", label = TRUE)
FeaturePlot(fullseurat, features = c("CD4"), order = TRUE, pt.size = 1)
FeaturePlot(fullseurat, features = c("CD8A"), order = TRUE, pt.size = 1)
# T cells = 0, 1, 3, 4, 5
# CD4 T cells = 0, 1, 5
# CD8 T cells = 4, 3
# B cells = 2, 8
# granulocytes = 9, 10
```


```{r}
keep <- rownames(fullseurat[[]])[which(fullseurat[["clusters_wholedataset"]] == "0" |
                                             fullseurat[["clusters_wholedataset"]] == "1" |
                                             fullseurat[["clusters_wholedataset"]] == "3" |
                                             fullseurat[["clusters_wholedataset"]] == "4" |
                                             fullseurat[["clusters_wholedataset"]] == "5")]
```

```{r}
subsetseurat <- subset(fullseurat, cells = keep)
```

```{r}
saveRDS(subsetseurat, file = paste0(outdir, sampleID, "_subset.RDS"))
```


