---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
```


```{r}
df <- readRDS("/scripts/11b_RunClusteringRes0.4/out_obj/allintegratedClustered_Seurat2.RDS")

outdir <- "/scripts/12_RunBasicQC/outdir_samplewise/"

Idents(df) <- "sample"
```

```{r}
DimPlot(df, group.by = "phase")
ggsave(filename = paste0(outdir, "phase.jpeg"), width = 8, height = 8)

phase_meta <- as.matrix(table(df[[c("integrated_snn_res.0.4", "phase")]]))
write.table(phase_meta, file = paste0(outdir, "phase_metadata.txt"), sep = "\t", quote = FALSE, col.names = NA)
```


```{r}
DefaultAssay(df) <- "RNA"
df[["percent.mt"]] <- PercentageFeatureSet(df, pattern = "^MT-")
df[["percent.rb"]] <- PercentageFeatureSet(df, pattern = "^RPS|^RPL")
```

```{r}
VlnPlot(df, features = "percent.mt")
ggsave(filename = paste0(outdir, "mito_vln.jpeg"), width = 8, height = 8)
FeaturePlot(df, features = "percent.mt", order = TRUE)
ggsave(filename = paste0(outdir, "mito_umap.jpeg"), width = 8, height = 8)

VlnPlot(df, features = "percent.rb")
ggsave(filename = paste0(outdir, "ribo_vln.jpeg"), width = 8, height = 8)
FeaturePlot(df, features = "percent.rb", order = TRUE)
ggsave(filename = paste0(outdir, "ribo_umap.jpeg"), width = 8, height = 8)

VlnPlot(df, features = "nFeature_RNA")
ggsave(filename = paste0(outdir, "nFeature_vln.jpeg"), width = 8, height = 8)
FeaturePlot(df, features = "nFeature_RNA", order = TRUE)
ggsave(filename = paste0(outdir, "nFeature_umap.jpeg"), width = 8, height = 8)

VlnPlot(df, features = "nCount_RNA")
ggsave(filename = paste0(outdir, "nCount_vln.jpeg"), width = 8, height = 8)
FeaturePlot(df, features = "nCount_RNA", order = TRUE)
ggsave(filename = paste0(outdir, "nCount_umap.jpeg"), width = 8, height = 8)
```

```{r}
FeatureScatter(df, feature1 = "nCount_RNA", feature2 = "percent.mt")
ggsave(filename = paste0(outdir, "nCountVSmito.jpeg"), width = 8, height = 8)

FeatureScatter(df, feature1 = "nCount_RNA", feature2 = "percent.rb")
ggsave(filename = paste0(outdir, "nCountVSribo.jpeg"), width = 8, height = 8)

FeatureScatter(df, feature1 = "percent.mt", feature2 = "percent.rb")
ggsave(filename = paste0(outdir, "mitoVSribo.jpeg"), width = 8, height = 8)

FeatureScatter(df, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
ggsave(filename = paste0(outdir, "nCountVSnFeature.jpeg"), width = 8, height = 8)
```

# Plot UMAPs of the different variables

```{r}
DimPlot(df, group.by = "sample", shuffle = TRUE)
ggsave(filename = paste0(outdir, "UMAP_sample.pdf"), width = 5, height = 5)
DimPlot(df, group.by = "injury", shuffle = TRUE)
ggsave(filename = paste0(outdir, "UMAP_innjury.pdf"), width = 5, height = 5)
DimPlot(df, group.by = "tissue", shuffle = TRUE)
ggsave(filename = paste0(outdir, "UMAP_tissue.pdf"), width = 5, height = 5)
DimPlot(df, group.by = "drug", shuffle = TRUE)
ggsave(filename = paste0(outdir, "UMAP_drug.pdf"), width = 5, height = 5)
DimPlot(df, group.by = "injurydrug", shuffle = TRUE)
ggsave(filename = paste0(outdir, "UMAP_injurydrug.pdf"), width = 5, height = 5)
```

What is the makeup of each cluster?

```{r}
data <- as.data.frame(table(df[[c("integrated_snn_res.0.4", "sample")]]))
data <- reshape2::melt(data)
```

```{r}
write.table(data, file = paste0(outdir, "clusterwise_samplecounts.txt"), sep = "\t", quote = FALSE, col.names = NA)

ggplot(data, aes(fill = sample, y = value, x = integrated_snn_res.0.4)) + geom_bar(position = "stack", stat = "identity")
ggsave(filename = paste0(outdir, "samplebar_all_number.jpeg"), width = 8, height = 8)

ggplot(data, aes(fill = sample, y = value, x = integrated_snn_res.0.4)) + geom_bar(position = "fill", stat = "identity")
ggsave(filename = paste0(outdir, "samplebar_all_percent.jpeg"), width = 8, height = 8)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) + geom_bar(position = "stack", stat = "identity")
ggsave(filename = paste0(outdir, "samplebar_blood_number.jpeg"), width = 8, height = 8)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) + geom_bar(position = "fill", stat = "identity")
ggsave(filename = paste0(outdir, "samplebar_blood_percent.jpeg"), width = 8, height = 8)

data[grep("cord", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) + geom_bar(position = "stack", stat = "identity")
ggsave(filename = paste0(outdir, "samplebar_cord_number.jpeg"), width = 8, height = 8)

data[grep("cord", data$sample),] %>% ggplot(aes(fill = sample, y = value, x = integrated_snn_res.0.4)) + geom_bar(position = "fill", stat = "identity")
ggsave(filename = paste0(outdir, "samplebar_cord_percent.jpeg"), width = 8, height = 8)
```

Flip the data the other way, plot each sample and break down by cluster

```{r}
palette <- c(`0` = "yellowgreen",
             `1` = "#D1147F",
             `2` = "gold",
             `3` = "darkmagenta",
             `4` = "orangered",
             `5` = "lightseagreen",
             `6` = "navyblue",
             `7` = "dodgerblue",
             `8` = "darkgreen",
             `9` = "hotpink",
             `10` = "darkorchid")

#palette2 <- met.brewer("Signac", n = 14, type = "discrete")
#palette2 <- sample(palette2, 14)
```


```{r}
ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette)
ggsave(filename = paste0(outdir, "clusterbar_all_number.jpeg"), width = 8, height = 8)

ggplot(data, aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = palette)
ggsave(filename = paste0(outdir, "clusterbar_all_percent.jpeg"), width = 8, height = 8)


data[grep("cord", data$sample),] %>% ggplot(aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette)
ggsave(filename = paste0(outdir, "clusterbar_cord_number.jpeg"), width = 8, height = 8)

data[grep("blood", data$sample),] %>% ggplot(aes(fill = integrated_snn_res.0.4, y = value, x = sample)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = palette)
ggsave(filename = paste0(outdir, "clusterbar_blood_number.jpeg"), width = 8, height = 8)
```
