---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
```

```{r}
outdir <- "/scripts/12b_CompareSimilarClusters/outdir/"

df <- readRDS("/scripts/11b_RunClusteringRes0.4/out_obj/allintegratedClustered_Seurat2.RDS")

Idents(df) <- "integrated_snn_res.0.4"
DefaultAssay(df) <- "RNA"
```

# compare cluster 2 and cluster 8 (2x naive memory B)

```{r}
NaiveMemB.markers <- FindMarkers(df, min.pct = 0.25, logfc.threshold = 0.25, ident.1 = 2, ident.2 = 8)
NaiveMemB.markers <- NaiveMemB.markers %>% filter(p_val_adj <= 0.05)

# add in direction
NaiveMemB.markers$geneID <- rownames(NaiveMemB.markers)
NaiveMemB.markers <- mutate(NaiveMemB.markers, cluster = ifelse(avg_log2FC > 0, 2, 8))
# add in absolute log2FC
NaiveMemB.markers <- mutate(NaiveMemB.markers, avg_log2FC_abs = abs(avg_log2FC))
# add in the average difference between clusters
NaiveMemB.markers <- mutate(NaiveMemB.markers, diff_pct_abs = abs(pct.1 - pct.2))

NaiveMemB.markers_top10 <- NaiveMemB.markers %>% group_by(cluster) %>% slice_max(order_by = avg_log2FC_abs, n = 10)
NaiveMemB.markers_top10diff <- NaiveMemB.markers %>% group_by(cluster) %>% slice_max(order_by = diff_pct_abs, n = 10)


write.table(NaiveMemB.markers, file = paste0(outdir, "NaiveMemB", "_allmarkers.txt"), quote = FALSE, col.names = NA, sep = "\t")
write.table(NaiveMemB.markers_top10, file = paste0(outdir, "NaiveMemB", "_top10.txt"), quote = FALSE, col.names = NA, sep = "\t")
write.table(NaiveMemB.markers_top10diff, file = paste0(outdir, "NaiveMemB", "_top5MostDiffExpPct.txt"), quote = FALSE, col.names = NA, sep = "\t")

DotPlot(df, features = NaiveMemB.markers_top10$geneID) + RotatedAxis()
ggsave(filename = paste0(outdir, "NaiveMemB", "_dotplot.jpeg"), width = 10)
DotPlot(df, features = NaiveMemB.markers_top10$geneID, idents = c(2,8)) + RotatedAxis()
ggsave(filename = paste0(outdir, "NaiveMemB", "_dotplot_RelevantClustOnly.jpeg"), width = 10, height = 4)

DotPlot(df, features = NaiveMemB.markers_top10diff$geneID) + RotatedAxis()
ggsave(filename = paste0(outdir, "NaiveMemB", "_dotplot_top10DiffExpPct.jpeg"), width = 8)
DotPlot(df, features = NaiveMemB.markers_top10diff$geneID, idents = c(2,8)) + RotatedAxis()
ggsave(filename = paste0(outdir, "NaiveMemB", "_dotplot_top10DiffExpPct_RelevantClustOnly.jpeg"), width = 10, height = 4)
```

```{r}
MostDistinctGenes <- intersect(NaiveMemB.markers_top10diff$geneID, NaiveMemB.markers_top10$geneID)
dir.create(paste0(outdir, "/NaiveMemB_distinctivegenes"))
for (i in MostDistinctGenes) {
  FeaturePlot(df, features = i, order = TRUE)
  ggsave(filename = paste0(outdir, "/NaiveMemB_distinctivegenes/", i, "_UMAP.jpeg"), width = 5, height = 5)
}
```


# Naive CD8 (cluster 3) and memory CD8 (cluster 4)

```{r}
CD8.markers <- FindMarkers(df, min.pct = 0.25, logfc.threshold = 0.25, ident.1 = 3, ident.2 = 4)
CD8.markers <- CD8.markers %>% filter(p_val_adj <= 0.05)

# add in direction
CD8.markers$geneID <- rownames(CD8.markers)
CD8.markers <- mutate(CD8.markers, cluster = ifelse(avg_log2FC > 0, 3, 4))
# add in absolute log2FC
CD8.markers <- mutate(CD8.markers, avg_log2FC_abs = abs(avg_log2FC))
# add in the average difference between clusters
CD8.markers <- mutate(CD8.markers, diff_pct_abs = abs(pct.1 - pct.2))

CD8.markers_top10 <- CD8.markers %>% group_by(cluster) %>% slice_max(order_by = avg_log2FC_abs, n = 10)
CD8.markers_top10diff <- CD8.markers %>% group_by(cluster) %>% slice_max(order_by = diff_pct_abs, n = 10)


write.table(CD8.markers, file = paste0(outdir, "CD8", "_allmarkers.txt"), quote = FALSE, col.names = NA, sep = "\t")
write.table(CD8.markers_top10, file = paste0(outdir, "CD8", "_top10.txt"), quote = FALSE, col.names = NA, sep = "\t")
write.table(CD8.markers_top10diff, file = paste0(outdir, "CD8", "_top10MostDiffExpPct.txt"), quote = FALSE, col.names = NA, sep = "\t")

DotPlot(df, features = CD8.markers_top10$geneID) + RotatedAxis()
ggsave(filename = paste0(outdir, "CD8", "_dotplot.jpeg"), width = 10)
DotPlot(df, features = CD8.markers_top10$geneID, idents = c(3,4)) + RotatedAxis()
ggsave(filename = paste0(outdir, "CD8", "_dotplot_RelevantClustOnly.jpeg"), width = 10, height = 4)

DotPlot(df, features = CD8.markers_top10diff$geneID) + RotatedAxis()
ggsave(filename = paste0(outdir, "CD8", "_dotplot_top10DiffExpPct.jpeg"), width = 8)
DotPlot(df, features = CD8.markers_top10diff$geneID, idents = c(3,4)) + RotatedAxis()
ggsave(filename = paste0(outdir, "CD8", "_dotplot_top10DiffExpPct_RelevantClustOnly.jpeg"), width = 10, height = 4)
```

```{r}
MostDistinctGenes <- intersect(CD8.markers_top10diff$geneID, CD8.markers_top10$geneID)
dir.create(paste0(outdir, "/CD8_distinctivegenes"))
for (i in MostDistinctGenes) {
  FeaturePlot(df, features = i, order = TRUE)
  ggsave(filename = paste0(outdir, "/CD8_distinctivegenes/", i, "_UMAP.jpeg"), width = 5, height = 5)
}
``` 
