---
title: "R Notebook"
output: html_notebook
---

# just edit for each file and run

```{r}
library(dplyr)
```

```{r}
outdir <- "/scripts/13b_ProcessForGO/Samplewise/outdir/"
indir <- "/scripts/13_DEG/AllCellsTogether/4.1_SCIvsshamnaive_blood/outdir_SCIvsNot/"
sampleID <- "4.1_SCIvsshamnaive_blood"
```


```{r}
data_files <- list.files(indir, full.names = TRUE, recursive = TRUE, pattern = ".txt")

# List of the markers
all_markers_file <- data_files[grep("Rb", data_files, invert = TRUE)]
all_markers_file <- all_markers_file[grep("top10", all_markers_file, invert = TRUE)]

dropRb_markers_file <- data_files[grep("Rb", data_files)]
dropRb_markers_file <- dropRb_markers_file[grep("markers", dropRb_markers_file)]
dropRb_markers_file <- dropRb_markers_file[grep("top10", dropRb_markers_file, invert = TRUE)]
```

```{r}
prep_files_KeepRb <- function(myfile) {
  clusterID <- gsub(".*_", "", basename(myfile)) %>% gsub(".txt", "", .)
  df_temp <- read.delim(myfile, row.names = 1)
  if(nrow(df_temp) > 0) {
    df_temp <- mutate(df_temp, cluster = paste0(clusterID, "_", direction))
    df_temp$analysisID <- clusterID
    df_temp <- mutate(df_temp, avg_log2FC_abs = abs(avg_log2FC))
    df_temp <- df_temp %>% group_by(cluster) %>% arrange(desc(avg_log2FC_abs, by_group = cluster))
    return(df_temp) 
  }
}

prep_files_dropRb <- function(myfile) {
  clusterID <- basename(myfile) %>% gsub("_RemoveRbMt.txt", "", .) %>% gsub("markers_", "", .)
  df_temp <- read.delim(myfile, row.names = 1)
  if(nrow(df_temp) > 0) {
    df_temp <- mutate(df_temp, cluster = paste0(clusterID, "_", direction))
    df_temp$analysisID <- clusterID
    df_temp <- mutate(df_temp, avg_log2FC_abs = abs(avg_log2FC))
    df_temp <- df_temp %>% group_by(cluster) %>% arrange(desc(avg_log2FC_abs, by_group = cluster))
    return(df_temp) 
  }
}
```

```{r}
df <- lapply(all_markers_file, prep_files_KeepRb) %>% bind_rows()
rownames(df) <- seq(1:length(rownames(df)))
df <- mutate(df, analysis_cluster = paste0(cluster, "_", analysisID))
df <- df %>% group_by(cluster) %>% arrange(desc(avg_log2FC_abs, by_group = cluster))
write.table(df, file = paste0(outdir, sampleID, "_Markers_KeepSeparate.txt"), sep = "\t", quote =  FALSE, col.names = NA)

df_noRb <- lapply(dropRb_markers_file, prep_files_dropRb) %>% bind_rows()
rownames(df_noRb) <- seq(1:length(rownames(df_noRb)))
df_noRb <- mutate(df_noRb, analysis_cluster = paste0(cluster, "_", analysisID))
df_noRb <- df_noRb %>% group_by(cluster) %>% arrange(desc(avg_log2FC_abs, by_group = cluster))
write.table(df_noRb, file = paste0(outdir, sampleID, "_Markers_KeepSeparate_dropRbMt.txt"), sep = "\t", quote =  FALSE, col.names = NA)
```
